Repository PBento96/minishell, pull requests merged in 2025-01, with the labels that each got.

#27 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#28 Update README.md
  README.md
Labels: documentation

#29 Added Start of Main & Added Libft to Makefile
  .github/workflows/make.yml
  Makefile
  includes/libft/libft.a
  includes/make/vars.mk
  includes/minishell.h
  src/main.c
Labels: enhancement

#31 Dev
  .gitignore
  Makefile
  README.md
  includes/make/vars.mk
  includes/minishell.h
  src/main.c
  src/startup.c
Labels: documentation, enhancement

#32 Documentation changes
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation

#33 Libft norm fixes
  .github/pull_request_template.md
  Makefile
  includes/libft/Makefile
  includes/libft/libft.a
Labels: bug
